### ISSUE TITLE
A quick questions about the usage of spatialde

### ISSUE THREAD

**Issue by HelloWorldLTY** [PMBio/spatialde2-paper#1]
Hi, thanks for your great work. It seems that we can use fit_fast to deploy spatialde in the gpu core. However, for the output of spatialde2 fit_fast function, I cannot find the p-values and other statistics for testing. Moreover, it seems that the function test is still very slow.

Is there anything wrong in my understanding? Thanks.
![image](https://github.com/PMBio/spatialde2-paper/assets/43333475/dba8cf90-287e-4d2f-b8c5-8828e46678a8)

**Comment by ilia-kats** [comment]
No, that is correct. The `fit_fast` and `fit_detailed` functions only estimate the fraction of spatial variance and other parameters of the pattern, the `test` function is for testing only. The intended workflow is to run `test` first, and then run `fit_fast` or `fit_detailed` on the genes of interest. You can speed up `test` by passing `omnibus=True`, which uses a different (slightly less sensitive) kind of test.

**Comment by HelloWorldLTY** [comment]
Got it, thanks a lot.
