### ISSUE TITLE
AttributeError: module 'SpatialDE' has no attribute 'test'

### ISSUE THREAD

**Issue by endNone** [PMBio/spatialde2-paper#2]
Hello, I have encountered a problem：
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 1
----> 1 svg_full, _ = SpatialDE.test(data, omnibus=True)
      2 svg_full["total_counts"] = np.asarray(data.X.sum(axis=0)).squeeze()
      3 svg_full.to_pickle("ST8059048_svg_full.pkl")

AttributeError: module 'SpatialDE' has no attribute 'test'

**Comment by ilia-kats** [comment]
Which version of SpatialDE is this?

**Comment by endNone** [comment]
I switched from using the version on pip to the one on GitHub, and the issue has been resolved.
